version: '3.8'

services:
  english-bot:
    image: anselis/english-bot-images:latest
    container_name: english-bot
    ports:
      - "8080:8080"
    environment:
      DB_URL_PROD: "jdbc:mysql://db:3306/english_bot_db"
      DB_USERNAME_PROD: "${DB_USERNAME_PROD}"
      DB_PASSWORD_PROD: "${DB_PASSWORD_PROD}"
      BOT_NAME_PROD: "${BOT_NAME_PROD}"
      BOT_TOKEN_PROD: "${BOT_TOKEN_PROD}"
      SPRING_PROFILES_ACTIVE: "${SPRING_PROFILES_ACTIVE}"
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mysql:8.0
    container_name: english-bot-db
    environment:
      MYSQL_DATABASE: "english_bot_db"
      MYSQL_USER: "${DB_USERNAME_PROD}"
      MYSQL_PASSWORD: "${DB_PASSWORD_PROD}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  db_data:
