spring:
  application:
    name: ${SPRING_APP_NAME:english_bot}

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  bot:
    name: ${BOT_NAME:English5000WordsBot}
    token: ${BOT_TOKEN}

  flyway:
    enabled: true
    locations: classpath:db/migration
    outOfOrder: true
    encoding: UTF-8

server:
  address: 0.0.0.0
  port: ${SERVER_PORT:8080}
