spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:mysql://${DB_URL_PROD}
    username: ${DB_USERNAME_PROD}
    password: ${DB_PASSWORD_PROD}

bot:
  name: ${BOT_NAME_PROD}
  token: ${BOT_TOKEN_PROD}