# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: english bot cicd

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn clean install
      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: anselis/english-bot-images
          tags: latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Deploy to Hetzner Server
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.HETZNER_HOST }}
          username: ${{ secrets.HETZNER_USERNAME }}
          password: ${{ secrets.HETZNER_PASSWORD }}
          script: |
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            docker pull anselis/english-bot-images:latest
            docker stop english-bot || true
            docker rm english-bot || true
            docker run -d --name english-bot -p 8080:8080 \
              --restart unless-stopped \
              -e DB_URL_PROD="${{ secrets.DB_URL_PROD }}" \
              -e DB_USERNAME_PROD="${{ secrets.DB_USERNAME_PROD }}" \
              -e DB_PASSWORD_PROD="${{ secrets.DB_PASSWORD_PROD }}" \
          
              -e BOT_TOKEN_PROD="${{ secrets.BOT_TOKEN_PROD }}" \
              -e SPRING_PROFILES_ACTIVE="${{ secrets.SPRING_PROFILES_ACTIVE }}" \
              anselis/english-bot-images:latest